<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 15px; height: 80px">

# Project 4: Web Scraping Job Postings

Detailed instructions are in Readme.md 
My answers for this Project are split into several notebooks to make it easier to review key sections and make changes where needed. In 1.1, I work on cleaning the jobs data and EDA.

# NOTE: 
I have less than 1,000 listings. But most of the data, taken from a Government website, has the salary range, which is critical to the analysis. I have also used 20 different search items while scrapping for the listings and don't think it is wise to blindly broaden the search parameters further for the sake of fulfilling the the 1,000 listings criteria.

In [42]:
import numpy as np
import pandas as pd

### 1. DATA CLEANING OF JOBS DATA

In [3]:
jobs = pd.read_csv('../data/jobs.csv')

In [4]:
jobs = jobs.drop(columns = 'Unnamed: 0')

In [5]:
jobs.head()

,Company,Title,Salary_Range,Responsibilities,Requirements,Seniority,Employment_Type,Category,Address
0,HITACHI CONSULTING SINGAPORE PTE. LTD.,Senior Consultant (Data Scientist),"$6,000to$9,000",Roles & Responsibilities Problem solver with c...,Requirements Sound knowledge of machine learni...,Senior Executive,"Permanent, Contract",Information Technology,"PLAZA 8 @ CBP, 1 CHANGI BUSINESS PARK CRESCENT..."
1,TRAVELOKA SERVICES PTE. LTD.,Data Science Lead,"$10,000to$15,000","Roles & ResponsibilitiesAs a Data scientist, y...",RequirementsWe are looking for someone with: ...,Manager,Full Time,Information Technology,NaN
2,TRAVELOKA SERVICES PTE. LTD.,Senior Level Data Scientist,"$8,300to$15,000",Roles & ResponsibilitiesJob Description As a D...,Requirements Solid programming skills and und...,Executive,Permanent,Information Technology,NaN
3,TRAVELOKA SERVICES PTE. LTD.,Mid - Senior Level Data Scientist,"$6,100to$10,700","Roles & ResponsibilitiesAs a Data scientist, y...",Requirements Solid programming skills and und...,Executive,Permanent,Information Technology,NaN
4,TRAVELOKA SERVICES PTE. LTD.,Mid Level Data Scientist,"$4,300to$7,600","Roles & ResponsibilitiesAs a Data scientist, y...",Requirements Solid programming skills and und...,Executive,Permanent,Information Technology,NaN

#### On inspection, it appears 42 rows are completely empty due to dead links. Let's drop those.

In [6]:
jobs = jobs.dropna(axis=0, how='all')

In [7]:
jobs.shape

(932, 9)

In [8]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 932 entries, 0 to 974
Data columns (total 9 columns):
Company             932 non-null object
Title               932 non-null object
Salary_Range        875 non-null object
Responsibilities    932 non-null object
Requirements        932 non-null object
Seniority           932 non-null object
Employment_Type     932 non-null object
Category            932 non-null object
Address             729 non-null object
dtypes: object(9)
memory usage: 72.8+ KB

In [9]:
jobs.isnull().sum()

Company               0
Title                 0
Salary_Range         57
Responsibilities      0
Requirements          0
Seniority             0
Employment_Type       0
Category              0
Address             203
dtype: int64

In [10]:
# Replacing the missing addresses with "Undisclosed"
jobs['Address'] = jobs['Address'].fillna('Undisclosed')

#### 1.1 MINOR FEATURE ENGINGEERING TO SPLIT SALARY INTO LOW AND HIGH RANGE

In [11]:
salary_high_low = jobs['Salary_Range'].str.split('to', 1, expand=True)

In [12]:
salary_high_low.columns = ['Salary_Min', 'Salary_Max']

In [13]:
jobs = pd.concat([jobs, salary_high_low], axis = 'columns')

In [14]:
jobs = jobs.drop(columns = 'Salary_Range')

In [15]:
# Removing $ and comma from the salary columns
jobs['Salary_Min'] = jobs['Salary_Min'].map(lambda x : str(x).replace('$',''))
jobs['Salary_Max'] = jobs['Salary_Max'].map(lambda x : str(x).replace('$',''))
jobs['Salary_Min'] = jobs['Salary_Min'].map(lambda x : str(x).replace(',',''))
jobs['Salary_Max'] = jobs['Salary_Max'].map(lambda x : str(x).replace(',',''))

In [16]:
# Converting salary cols to numeric dtype
jobs['Salary_Min'] = pd.to_numeric(jobs['Salary_Min'], errors='coerce')
jobs['Salary_Max'] = pd.to_numeric(jobs['Salary_Max'], errors='coerce')

#### 1.2 ADJUSTING SOME SALARY FIGURES AND IMPUTING MISSING SALARIES

In [17]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 932 entries, 0 to 974
Data columns (total 10 columns):
Company             932 non-null object
Title               932 non-null object
Responsibilities    932 non-null object
Requirements        932 non-null object
Seniority           932 non-null object
Employment_Type     932 non-null object
Category            932 non-null object
Address             932 non-null object
Salary_Min          875 non-null float64
Salary_Max          875 non-null float64
dtypes: float64(2), object(8)
memory usage: 80.1+ KB

In [18]:
jobs.describe()

          Salary_Min     Salary_Max
count     875.000000     875.000000
mean     9423.897143   14646.446857
std     24692.445188   34250.884169
min      1800.000000    2000.000000
25%      4000.000000    6000.000000
50%      5000.000000    8000.000000
75%      7000.000000   11700.000000
max    380000.000000  405000.000000

#### It's clear from the table above there are some unusual salary numbers in the mix. AspenTech, for instance, is offering a salary of SGD380,000 to SGD405,000. A check on the jobs portal shows that the figure is indeed an annual renumeration [https://www.mycareersfuture.sg/job/vp-sales-aspentech-dbe12dc833aac79f3ccccb02c491b983]

#### Further checks show that these companies are using annual renumeration, which would have to be changed to monthly renumeration:
- DataRobot
- ONECONNECT FINANCIAL TECHNOLOGY 
- CISCO SYSTEMS
- MICROSOFT OPERATIONS
- RECORDED FUTURE PTE. LTD
- SYNECHRON TECHNOLOGIES SINGAPORE PTE. LTD
- AUTODESK ASIA
- HILTON INTERNATIONAL ASIA PACIFIC PTE LTD
- BEATHCHAPMAN (PTE. LTD.)
- PURE STORAGE SINGAPORE PTE. LIMITED
- FIREVISOR SYSTEMS PTE. LTD.
- FOURTH PARADIGM SOUTHEAST ASIA PTE. LTD
- NATIONAL UNIVERSITY OF SINGAPORE
- ASPENTECH PTE. LTD
- S.W.I.F.T. TERMINAL SERVICES PTE. LTD.
- UNDERWRITEME TECHNOLOGY SOLUTIONS LIMITED SINGAPORE BRANCH
- MERCER HEALTH & BENEFITS (SINGAPORE) PTE. LTD
- VISA WORLDWIDE PTE. LIMITED
- SABRE ASIA PACIFIC PTE. LTD
- Company Undisclosed (one entry)

In [19]:
#As suspected, companies offering "minimum" salary of 30,000 dollars were giving annual renumeration
jobs[jobs['Salary_Min'] > 30000]

,Company,Title,Responsibilities,Requirements,Seniority,Employment_Type,Category,Address,Salary_Min,Salary_Max
11,DATAROBOT SINGAPORE PTE. LTD.,Applied Data Science Associate,Roles & ResponsibilitiesLooking to move into D...,RequirementsMain Requirements Experience/Trai...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
19,DATAROBOT SINGAPORE PTE. LTD.,"Data Scientist, AI Services",Roles & ResponsibilitiesAI Services is a consu...,RequirementsMain Requirements * 3+ years of re...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
33,ONECONNECT FINANCIAL TECHNOLOGY (SINGAPORE) CO...,Intelligent Risk Data Scientist Manager / Assi...,"Roles & Responsibilities Develop AI Algorithm,...",Requirements More than 5 years (10 years for S...,Senior Executive,"Permanent, Full Time",Information Technology,Undisclosed,96000.0,120000.0
67,CISCO SYSTEMS (USA) PTE. LTD.,Senior Data Scientist,Roles & Responsibilities What You'll Do As ...,RequirementsWho You Are Do you thrive in a mul...,Professional,Full Time,Information Technology,"ONE MARINA BOULEVARD, 1 MARINA BOULEVARD 018989",170000.0,230000.0
104,DATAROBOT SINGAPORE PTE. LTD.,Business Intelligence Analyst - Machine Engine...,Roles & ResponsibilitiesWe are building a comp...,RequirementsRequirements 3+ years of experien...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
106,DATAROBOT SINGAPORE PTE. LTD.,Senior Backend Engineer,Roles & ResponsibilitiesDataRobot accelerates ...,RequirementsMain Requirements: 3+ years devel...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
108,DATAROBOT SINGAPORE PTE. LTD.,Quality Engineer,Roles & ResponsibilitiesDataRobot changes the ...,Requirements 3+ years of professional quality ...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
148,MICROSOFT OPERATIONS PTE LTD,Business Program Manager,Roles & ResponsibilitiesMicrosoft’s HIT team e...,RequirementsQualifications Behaviour and cha...,Non-executive,Full Time,Information Technology,Undisclosed,90000.0,135000.0
149,RECORDED FUTURE PTE. LTD.,"Director of Sales Engineering, APJ",Roles & ResponsibilitiesWant to be part of sha...,RequirementsQualifications Minimum of 3-5 yea...,Senior Management,Full Time,Information Technology,Undisclosed,180000.0,190000.0
157,DATAROBOT SINGAPORE PTE. LTD.,Software Engineer in Test,Roles & ResponsibilitiesThis position’s respon...,RequirementsSkills: Solid foundation in quali...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,100000.0,120000.0
162,DATAROBOT SINGAPORE PTE. LTD.,Data Science Engineer,Roles & ResponsibilitiesAs a Data Science Engi...,Requirements 5+ years of combined python Engin...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
253,SYNECHRON TECHNOLOGIES SINGAPORE PTE. LTD.,Senior Technology Specialist,Roles & ResponsibilitiesSynechron on behalf of...,RequirementsThe senior Technology specialist i...,"Manager, Professional",Full Time,Banking and Finance,"ONE RAFFLES PLACE, 1 RAFFLES PLACE 048616",120000.0,240000.0
374,MERCER HEALTH & BENEFITS (SINGAPORE) PTE. LTD.,Health and Benefits Consulting Analyst,Roles & ResponsibilitiesA global and prominent...,Requirements· Global and Regional account mana...,Fresh/entry level,Permanent,Consulting,"ASIA SQUARE TOWER 1, 8 MARINA VIEW 018960",45000.0,75000.0
426,AUTODESK ASIA PTE. LTD.,19WD32806_SAP ABAP / HANA Develop,Roles & ResponsibilitiesDo what’s next Would y...,RequirementsTechnical Skills Bachelor's degre...,Professional,"Permanent, Full Time",Information Technology,"SYMBIOSIS, 3 FUSIONOPOLIS WAY 138633",60900.0,121800.0
501,Company Undisclosed,Chief Financial Officer,Roles & ResponsibilitiesThe Chief Financial Of...,"RequirementsA Bachelor’s degree in Accounting,...",Senior Management,Permanent,Accounting / Auditing / Taxation,Undisclosed,380000.0,400000.0
517,HILTON INTERNATIONAL ASIA PACIFIC PTE LTD,"Manager, Digital and Marketing Analytics - Asi...",Roles & ResponsibilitiesThe Analytics Team ser...,RequirementsWhat are we looking for? A Manager...,Manager,"Permanent, Full Time",Marketing / Public Relations,"CENTENNIAL TOWER, 3 TEMASEK AVENUE 039190",80000.0,150000.0
560,BEATHCHAPMAN (PTE. LTD.),Data Engineer,Roles & Responsibilities• Leading online tra...,"RequirementsOn behalf of our client, BeathChap...",Manager,Permanent,Information Technology,Undisclosed,120000.0,140000.0
700,DATAROBOT SINGAPORE PTE. LTD.,Sales Development Representative (Japanese),Roles & ResponsibilitiesAs a Sales Development...,RequirementsExperience Required 2+ years of c...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,40000.0,60000.0
701,DATAROBOT SINGAPORE PTE. LTD.,Sales Development Representative (Korean),Roles & ResponsibilitiesAs a Sales Development...,RequirementsExperience Required 2+ years of c...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,40000.0,60000.0
723,PURE STORAGE SINGAPORE PTE. LIMITED,Digital Marketing Manager - APJ,Roles & ResponsibilitiesAbout Us Our ambitious...,RequirementsWhat You Bring To The Team Proven...,Manager,Full Time,Marketing / Public Relations,"100 AM, 100 TRAS STREET 079027",158000.0,237000.0
743,FIREVISOR SYSTEMS PTE. LTD.,Software Developer,Roles & ResponsibilitiesHIGHLIGHTS: Join our ...,RequirementsABOUT YOU: You have 2+ years of ...,"Non-executive, Junior Executive",Full Time,Engineering,32 CARPENTER STREET 059911,60000.0,80000.0
753,FOURTH PARADIGM SOUTHEAST ASIA PTE. LTD.,FPGA Application Developer (AI Platform),Roles & ResponsibilitiesFPGA Application Devel...,RequirementsREQUIREMENT This role will take re...,Professional,Permanent,Information Technology,"MARINA BAY FINANCIAL CENTRE, 12 MARINA BOULEVA...",120000.0,250000.0
797,NATIONAL UNIVERSITY OF SINGAPORE,Research Fellow,Roles & ResponsibilitiesWe are looking for a h...,"Requirements PhD in Computational Biology, Com...",Non-executive,Full Time,Others,21 LOWER KENT RIDGE ROAD 119077,58560.0,117120.0
870,ASPENTECH PTE. LTD.,Senior Principal Business Consultant,Roles & ResponsibilitiesAspenTech is a leading...,Requirements B.S. in Engineering with 10-15 ye...,Professional,"Permanent, Full Time",Consulting,"GALAXIS, 1 FUSIONOPOLIS PLACE 138522",140000.0,207000.0
871,ASPENTECH PTE. LTD.,"VP, Sales",Roles & ResponsibilitiesAspenTech is a leading...,Requirements Bachelor’s degree (Engineering/Te...,Senior Management,"Permanent, Full Time",Others,"GALAXIS, 1 FUSIONOPOLIS PLACE 138522",280000.0,405000.0
898,VISA WORLDWIDE PTE. LIMITED,Software Engineer,Roles & ResponsibilitiesCompany Description As...,RequirementsQualifications So what are we look...,Fresh/entry level,"Permanent, Full Time",Information Technology,Undisclosed,50000.0,65000.0
909,SYNECHRON TECHNOLOGIES SINGAPORE PTE. LTD.,Senior Full Stack Developer,"Roles & ResponsibilitiesSynechron, one of the ...",RequirementsSynechron are looking for a Full S...,"Middle Management, Professional, Executive, Se...",Full Time,Information Technology,"ONE RAFFLES PLACE, 1 RAFFLES PLACE 048616",70000.0,140000.0
913,DATAROBOT SINGAPORE PTE. LTD.,"Software Engineer, Machine Engineering","Roles & ResponsibilitiesAt DataRobot, we are p...",RequirementsRequirements: 3+ years of experie...,Professional,Permanent,Information Technology,80 ROBINSON ROAD 068898,90000.0,150000.0
943,SABRE ASIA PACIFIC PTE. LTD.,Associate Incentives Accounting,Roles & ResponsibilitiesSabre is a technology ...,RequirementsEDUCATION: Bachelor's degree in A...,Executive,Full Time,Accounting / Auditing / Taxation,"ABACUS PLAZA, 3 TAMPINES CENTRAL 1 529540",34700.0,64500.0
957,S.W.I.F.T. TERMINAL SERVICES PTE. LTD.,MANAGERIAL / SENIOR MANAGEMENT,Roles & ResponsibilitiesJob Title: Senior Prod...,RequirementsResponsibilities: Your responsibil...,"Senior Management, Manager",Permanent,Banking and Finance,80 ROBINSON ROAD 068898,275000.0,330000.0
960,UNDERWRITEME TECHNOLOGY SOLUTIONS LIMITED SING...,BI Analyst,Roles & Responsibilities The role will be expe...,Requirements Information gathering for new and...,Professional,Permanent,Insurance,Undisclosed,120000.0,160000.0
966,VISA WORLDWIDE PTE. LIMITED,Systems Engineer,Roles & ResponsibilitiesCompany Description As...,RequirementsQualifications BS or MS in Comput...,Fresh/entry level,"Permanent, Full Time",Information Technology,Undisclosed,50000.0,65000.0

In [20]:
# Converting min salaries from annual renumeration to monthly figures
jobs['Salary_Min'] = jobs.apply(lambda row: row['Salary_Min']/12
                                if row['Salary_Min'] > 30000
                                else row['Salary_Min'],
                                axis= 1)

In [21]:
# Converting max salaries from annual renumeration to monthly figures
jobs['Salary_Max'] = jobs.apply(lambda row: row['Salary_Max']/12
                                if row['Salary_Max'] > 30000
                                else row['Salary_Max'],
                                axis= 1)

In [22]:
# Creating an average salary column for easier comparison during modelling 
jobs['Salary_Average'] = (jobs['Salary_Min'] + jobs['Salary_Max'])/2
jobs['Salary_Average'] = jobs['Salary_Average'].round(1)

#### 1.3 IMPUTING MISSING SALARY FIGURES

In [23]:
jobs.describe()

         Salary_Min    Salary_Max  Salary_Average
count    875.000000    875.000000      875.000000
mean    5685.824762   8866.292571     7276.058857
std     2822.930481   4256.999466     3454.453739
min     1800.000000   2000.000000     1900.000000
25%     4000.000000   6000.000000     4750.000000
50%     5000.000000   8000.000000     6500.000000
75%     7000.000000  11300.000000     9000.000000
max    31666.666667  33750.000000    32500.000000

#### The salary numbers now look more in line with what we know about the Singapore job market and the salary expectations in the data industry here. There are still some outliers, as we can see from the max salary figures above. As such, I would use the median instead to impute the missing salary figures.

In [24]:
jobs['Salary_Min'] = jobs['Salary_Min'].fillna(5000)
jobs['Salary_Max'] = jobs['Salary_Max'].fillna(8000)
jobs['Salary_Average'] = jobs['Salary_Average'].fillna(6500)

#### 1.4 REMOVE REPETITIVE WORDS SCOOPED UP DURING SCRAPPING
The web scrapping repeatedly picked up words like "Roles & Responsibilities" and "PTE. LTD." which won't be useful in the analysis. Let's get rid of them ahead of the modelling.

In [25]:
jobs['Responsibilities'] = jobs['Responsibilities'].str.replace('Roles & Responsibilities', '')

In [26]:
jobs['Requirements'] = jobs['Requirements'].str.replace('Requirements', '')

In [27]:
jobs['Company'] = jobs['Company'].str.replace('PTE. LTD.', '')
jobs['Company'] = jobs['Company'].str.replace('PTE LTD', '')
jobs['Company'] = jobs['Company'].str.replace('PRIVATE LIMITED', '')
jobs['Company'] = jobs['Company'].str.replace('LIMITED', '')
jobs['Company'] = jobs['Company'].str.replace('PTE.', '')
jobs['Company'] = jobs['Company'].str.replace('LTD.', '')

#### 1.5 DELETING ON UNSUITABLE ROWS PICKED UP DURING SCRAPING
Web-scraping is not always precise. Combined with the broad-nature of data science jobs and the general vagueness which some companies approach their job postings, it's no surprise that a check on the job title alone throws up some entries which clearly don't meet the criteria for this project.

In [28]:
jobs['Title'].unique()

array(['Senior Consultant (Data Scientist)', 'Data Science Lead',
       'Senior Level Data Scientist', 'Mid - Senior Level Data Scientist',
       'Mid Level Data Scientist', 'Data Scientist',
       'Data Scientist (Project Manager)', 'Senior Data Scientist',
       'Applied Data Science Associate', 'SENIOR DATA SCIENTIST',
       'Business Data Scientist',
       'AVP, Data Scientist, Analytics & Innovation, Group Legal, Compliance and Secretariat (WD03653)',
       'Manager, Data and Analytics, Advisory',
       'Data Scientist, AI Services',
       'Sr Data Scientist (Exp in ML, Python, R and Bidata Tech is Must)',
       'Data Engineer', 'Field Data Scientist',
       'SVP, Big Data and Customer Experience Optimisation',
       'Junior Data Scientist',
       'Intelligent Risk Data Scientist Manager / Assistant Manager',
       'Data Transformation Scientist', 'ETL Developer (ITSR)',
       'Data Scientist Analyst', 'Lead Data Scientist',
       'Assoc, Data Scientist (BAU) Operations Intelligence, CBG Ops, Technology and Operations (WD03348)',
       'Data Scientist (Economist)', 'Presales Specialist - Data Science',
       'Data Engineer (Ref 22998)', 'Vice President, Data Science',
       'Senior Manager, Data Engineer', 'DATA Scientist',
       'Data scientist',
       'PI, Enterprise Intelligence (Data Scientist) Senior Manager (Financial Services), Advisory SG',
       'Big Data Engineer', 'Junior Data Analyst',
       'Scientist (Data Analytics), I2R / A*STAR',
       'Data Engineer, Data Governance (1 Year Contract)',
       'Fab10 Data Science Engineer / Data Scientist',
       'Azure Data Analyst',
       'VP, Data Scientist, Investment and Trading Technology, Technology and Operations (WD00504)',
       'AVP, Data Scientist, Investment and Trading Technology, Technology and Operations (WD00504)',
       'Data Scientist (Natural Language Processing)',
       'Senior Data Platform Engineer',
       'Data Scientist, Credit Risk - Visa Consulting & Analytics',
       'Postdoctoral Fellow / Research Fellow (Data Analytics) / Data Scientist',
       'Contract (Senior), Financial Crime Analytics – Internal & External Fraud, Group Compliance (WD00340)',
       'Research Associate - Bioinformatics Analyst (Pathology)',
       'Staff Software Engineer',
       'SVP, Program Manager (Data Analytic), Institutional Banking Group Technology, T&O (WD03269)',
       'Senior Data Analyst', 'Senior Hadoop Engineer', 'Research Fellow',
       'NetSuite Administrator', 'Lecturer / Senior Lecturer',
       'Business Intelligence Analyst - Machine Engineering',
       'Associate Director, Enterprise Analytics',
       'Senior Backend Engineer', 'Head Of Data Analytics',
       'Quality Engineer',
       'Research Fellow (1-year contract),\xa0 Living Analytics Research Centre',
       'Research Associate - Bioinformatics Analyst',
       'Pre-Doctoral Research Associate / Assistant',
       'Associate, Data Engineer', 'Regional Sales Operations Lead, APAC',
       'Data Science Analyst', 'PRODUCT MANAGER (DEX)',
       'Full Stack Developer', 'Senior Research Fellow',
       'Field Operation Engineer - Big Data Engineer',
       'Senior Java Full Stack Developer',
       'Research Scientist (1-year contract),\xa0 Living Analytics Research Centre',
       'Associate / AVP, Research Engineer', 'Assistant Professor',
       'Marketing Analytics Manager', 'Datawarehouse Engineer',
       'Senior Research Scientist (1-year contract), Living Analytics Research Centre',
       'Instructor in Interactive Media Design (Educator Track)',
       'Channel Partner Recruitment Manager', 'APJ Media Manager',
       'UX Researcher',
       'Associate General Manager- Digital and Analytics',
       'Data Engineer  /  Analyst', 'Information Technology  Specialist',
       'Vice President, Enterprise Data Warehouse',
       'Business Analyst, Customer and Digital Analytics',
       'Business Program Manager', 'Director of Sales Engineering, APJ',
       'Data Science Engineer', 'Data Science',
       'People Analytics Lead, Senior Manager',
       'Senior Manager  /  Director , Product Management',
       'Senior / Data Engineer (Data Science Team)', 'Data Analyst, APAC',
       'Business Integrity Associate, Technical',
       'Software Engineer in Test',
       'MCT Global Planning Mfg Data Science Engineer',
       'SENIOR DATA ANALYST', 'Senior Machine Learning Engineer',
       'Growth Marketer (Lifecycle)',
       'Research Associate (Data Science) - EEE / INFINITUS',
       'Research Engineer, IHPC', 'Scientist (CS), IHPC',
       'Senior Scientist', 'Data Science Consulting',
       'Marketing Science Partner', 'Product Designer',
       'Program Director, IHPC', 'Project Manager', 'Software Engineer',
       'Business Fraud Program Manager',
       'Data Specialist (Recognition Services)', 'Research Associate',
       'Project Officer', 'AVP / VP (Investment Services Public Markets)',
       'Product Manager', 'Senior Technical Program Manager',
       'Regional Head of Agent Marketing (Engagement)',
       'SVP, Technical Delivery Manager, Middle Office Technology, Technology & Operations (WD02651)',
       'VP, Technical Delivery Manager, Middle Office Technology, Technology & Operations (WD02651)',
       'Mid Level Data Analyst', 'Platform Engineer',
       'Data Analytics Lead', 'CRM Data Analyst',
       'Technical Data Analyst', 'Data Analyst',
       'Data Management Analyst-Operations (Financial Institution / Town)',
       'Supply Chain Planning Anaylst', 'Data Analyst (Fairprice)',
       'Business Analyst (NTUC First Campus, Data Analytics)',
       'Analyst, Static Data Maintenance Specialist, SG-Wealth Mgmt Ops, T&O (WD03266)',
       'Senior Business Data Analyst', 'Business Analyst (Data)',
       'Data Planner', 'DATA ANALYST',
       'Associate, Advisory Data and Analytics',
       'Data Analyst (Vietnamese language proficient)',
       'Data Analyst at Viki Inc', 'data analyst',
       'HR Data Analyst / MNC / Central / 5 days week / 1 year contract',
       'AVP, Senior Data Analyst, Middle Office Technology, Technology and Operations - (WD03337)',
       'Senior Associate, Senior Data Analyst, Middle Office Technology, Technology and Operations-(WD03337)',
       'Industrial Placement - Data Analytics and Support Analyst',
       'Test Analyst', 'Data analyst', 'Data Analyst - Singapore',
       'Junior - Mid Level Data Analyst',
       'Data Analyst - Consumer Banking',
       'Data Analyst, Google Pay - Singapore', 'Cloud and Data analyst',
       'Operations Analyst - Reference Data Services',
       'Junior Data Analyst - SQL (Training Program for 15th April to 14th Jan 2020)',
       'Data Analyst, Data Management', 'Big Data Consultant',
       '2019 Market Data Analyst', 'Sr Data Analyst',
       'Data Analyst - Migration Coordinator', 'Data Analyst (Migration)',
       'iTero Data and Reporting Analyst',
       'Senior Project Manager, Analytics',
       'Senior Technology Specialist', 'Lead Database Analyst',
       'Data Visualisation Engineer (West)',
       'Digital Marketing Executive', 'Finance & Control Director',
       'Manager', 'management manager', 'Data Migration Manager',
       'Director', 'Security Operations Center (SOC) Analyst',
       'Senior Associate, Institutional Banking Group, GTS-SME Cash Commercialisation Specialist - (WD03694)',
       'AVP, Institutional Banking Group, GTS-SME Cash Commercialisation Specialist - (WD03694)',
       'IT Data & Analytics Manager (FP&A)',
       'Senior Staff Technical Program Manager', 'HSE Consultant',
       'CRM Manager', 'Logistic and Procurement Executive',
       'Technical Project Manager', 'Human Resource Executive',
       'Manager, Risk & Compliance',
       'Senior Consultant – Life Insurance, non-life, reinsurance',
       'Manager - Audit ( Data Analytics)',
       'Human Resource & Administrative Officer', 'Senior Manager',
       'Researcher (Intelligent Data Analytics)',
       'Data Analytics Specialist',
       'Senior Manager, Data and Analytics, Advisory',
       'Asia Product Manager', 'Restaurant Manager',
       'Manufacturing Software Engineer', 'Analyst',
       'Cloud Database Admin', 'Project Analyst', 'Lead Project Manager',
       'Director of Applications', 'Software Analyst',
       'Research Engineer (Data Analytics), I2R (A*STAR)',
       'Solution Architect',
       'Research Engineer (Cyber Security&Intelligence), I2R / A*STAR',
       'Research Engineer (Visual Intelligence), I2R / A*STAR',
       'Strategic Marketing Analyst, Scalable Marketing Solutions - Singapore',
       'Research Engineer (Human language Technologies) /  I2R (A*STAR)',
       'Talent Acquisition Manager', 'HR and Admin Executive',
       'Data ML Engineer', 'Manager (ECTD) /  I2R(A*STAR)',
       'Scientist (Robotics & Autonomous Systems), I2R / A*STAR',
       'DevOps Engineer', 'Back-end Engineer',
       'Senior Solution Architect', 'Senior Enterprise Architect',
       'VP, Enterprise Architect', 'VP, Credit Risk Review',
       'Manager (Electronics)', 'Ethics Manager',
       'data analytics manager', 'senior officer',
       'Research Engineer (Deep Learning 2.0)  /  I2R (A*STAR)',
       'Associate Analyst Mastercard Graduate Development Program',
       'Environmental Manager  /  Assistant',
       'Scientist (Deep Learning 2.0), I2R / A*STAR',
       'IT Audit Manager  /  $7000 Basic + 2VB  /  CBD  /  Immediate !!!',
       'Industry Development Manager, I2R / A*STAR',
       'Software Development Consultant',
       'Faculty Positions in Construction Automation - Civil Engineering',
       'Senior Manager, Postgraduate Career Services (3-year contract), LKCSB',
       'HR Practitioner', 'Account Manager', 'Lead  Analyst',
       'Application Support Operations Specialist', 'Product Director',
       'Operations & Maintenance Engineer',
       'VP, Technology Auditor, Group Audit (190000UV)',
       'AVP, Technology Auditor, Group Audit (190000UV)', 'Space Planner',
       'Credit Risk Model Validation, AVP-VP',
       'Senior /  Executive, Marketing Communications',
       'Research Analyst', 'Business Operations and Marketing Executive',
       'Customer Engineer, Data Analytics Specialist, Google Cloud - Singapore',
       'SIS - Assistant Professor of Information Systems (Education / Practice), SCPS',
       'Support Analyst', 'SEA Associate Account Manager, Media',
       'Mobile Product Manager', 'Associate / AVP, Facilities Management',
       'Audience Strategy Specialist',
       'Digital Marketing Executive (Wedding Services Industry / Central Area / Up to 2.8K)',
       'Account Manager (E-Commerce)', 'Development Engineer',
       'Business Analyst', 'Manager / Senior Manager - Risk Advisory',
       'Director  /  Senior Manager, Indirect Tax , APTC, Singapore',
       'Health and Benefits Consulting Analyst', 'Lead Reseacher',
       'Implementation Engineer', 'VP, Sales', 'Risk Assurance - Manager',
       'Risk Assurance - Associate',
       'IT Analyst (Fresh School Leaver are Welcome)',
       'Risk Assurance - Assistant Manager',
       'Business intelligence PMO Manager',
       'Technology Risk Manager (Data Analytics), Advisory, Singapore',
       'HR cum Admin Assistant [ Kallang Area, 5 Days, 1 Year Exp As HR]',
       'RISK ASSURANCE - DATA & ANALYTICS ASSOCIATE', 'Deputy Director',
       'Big data Presales',
       'Senior Executive / Executive, Operations (Community Networks for Seniors)',
       'HR & Admin Assistant', 'SENIOR ADMINISTRATIVE MANAGER',
       'Assistant Manager',
       'Senior Manager, System Operations (Ref 22991)',
       'IT BUSINESS ANALYST', 'Management Consultant - Technology',
       'Deputy General Manager', 'Strategic Director',
       'Associate Director, Business Intelligence and Investigations',
       'Senior Strategy Director',
       'Recruitment Consultant - Technology ( Cyber Security)',
       'Manager, Mechanical',
       'Assistant Director (Data Analytics) (JD#5030)',
       'Operations, Securities Division Operations, Equities Trading Services, Analyst',
       'Operations, Reg & Control Ops, Regulatory Ops - Derivatives Regulatory Reporting - Associate (51814)',
       'Operations, Regulatory Operations - Derivatives Regulatory Reporting - Executive Director  (51290)',
       'Marketing Executive', 'HR Executive', 'HR OFFICER',
       'Events Sales Manager',
       'Principal Research Engineer (Human Language Technologies), I2R / A*STAR',
       'Manager /  Senior Manager', '19WD32806_SAP ABAP / HANA Develop',
       'Scientist (Human Language Technologies, I2R / A*STAR)',
       'Software Engineer (Analytics, Big Data)', 'IT Quant',
       'Market Analyst', 'Platform Delivery Lead',
       'Senior Software Developer', 'DATA SCIENTISTS',
       'Operations, Securities Division Operations, Equities Trading Services Operations, Associate (51430)',
       'Front-End Developer', 'Senior Manager to Director',
       'Data Analytics – IT Supply Chain',
       'CIB - Neovest Account Manager — Market Data & Analytics Services – Vice President',
       'Research Engineer (Data Analytics)',
       'VP / Dir - Head of Service Transformation', 'Sales Executive',
       'Finance and Admin Executive', 'IT Business Analysts',
       'Business Analyst - Factory Integration',
       'Engineering Manager - Transport', 'SAP Consultant (SD Module)',
       'Supplier Quality Management Assistant Manager',
       'Senior Manager - Data Analytics (Content)',
       'VP, Senior Data Engineer Consultant, CBG and Big Data Analytics Technology, T&O (1800059H)',
       'AVP, Senior Data Engineer Consultant, CBG and Big Data Analytics Technology, T&O (1800059H)',
       'Digital Strategy Executive', 'IT Technical Manager',
       'Program Advisor', 'Financial Consultant',
       'Principal / Senior Engineer (Data Analytics & AI)',
       'Scientific Director (Ref: IRG_2019_001)',
       'Research Assistant / Research Associate / Postdoctoral Fellow / Research Fellow',
       'Big Data Solution Architect', 'Client Service Outbound Executive',
       'Enterprise Data Architect', 'Lead Solution Architect',
       'Regional Expansion Manager',
       'Senior Executive / Executive, System',
       'Senior / Business Analyst', 'FP&A Controller',
       'Sales Operations Executive - AP Cloud',
       'Channel Insights Manager',
       'Business Analytics & Insights – Retail Bank Segments & Sales Distribution',
       'Principal Analyst - Digital Retail System', 'Product Analyst',
       'Analytics Business Development Manager / Senior Manager',
       'Sales Operations Specialist', 'Business Analytics Specialist',
       'Chief Financial Officer',
       'Head of Business Intelligence and Analytics',
       'AVP, Investment Advisory – Business Infrastructure and Strategy, Private Banking (WD02311)',
       'Assistant Vice President, E-commerce',
       'Analyst /  Senior Analyst',
       'AP Senior Sales Operation Executive - Cloud',
       'SENIOR FINANCIAL ANALYST',
       'Sales Operations and Business Analysis Executive',
       'FP & A Manager',
       'Analyst, Financial Crime Analytics – Transaction Surveillance, Group Compliance - (WD03638)',
       'Financial Planning & Analytics Analyst',
       '2019 Financial Product Analytics & Sales Graduate Program - Indonesian / Japanese / Thai Speakers',
       'VP, Financial Crime Analytics – Transaction Monitoring, Group Compliance (WD02882)',
       'AVP, Financial Crime Analytics – Transaction Monitoring, Group Compliance (WD02882)',
       'Senior Lecturer, University',
       'Manager, Digital and Marketing Analytics - Asia Pacific',
       'Manager  /  Senior Manager Regional Marketing',
       'Head of Marketing and Digital Product Analytics',
       'Manager  /  Senior Manager, Regional Marketing (GrabWheels)',
       'Regional Marketing Manager', 'Marketing Analytics Consultant',
       'Manager, Marketing Analytics',
       'Junior Analyst, Marketing Business Intelligence',
       'Marketing Manager',
       'Admin Assistant, Research Department (6 months contract)',
       'Data Visualisation Developer', 'Lecturer', 'Senior Lecturer',
       'Senior Associate', 'Information System Manager',
       'IT Security Manager  (Central Area- Permanent Role)',
       'Data Center Engineer (Operations)',
       'Data Operations - Asset Management',
       'Officer, Change Support, Reference Data Services Operations',
       'Data Center Operations Engineer',
       'Executive, Data Centre Operations',
       'Associate, Data Engineer, Consumer Banking, Technology and Operations (WD03017)',
       'VP, CAP Data Engineer, Middle Office Tech, Technology & Operations (WD02988)',
       'Attractive L2 Support Engineer(Data Center Operations) opening in Singapore',
       'Content Analyst', 'Data Strategist',
       'Data Engineer (5 days, Orchard, $3500-4000)',
       'Data Center Support Engineer', 'Data Engineer (Ref 22360)',
       'Senior Level Data Engineer', 'Data Centre Engineer',
       'Mid - Senior Level Data Engineer', 'Mid Level Data Engineer',
       'Junior - Mid Level Data Engineer', 'Data  /  DevOps Engineer',
       'Senior Database Consultant - Big Data Engineer',
       'Data Governance Engineer', 'Data Analysis Engineer',
       'Technical Services Engineer (Technical Data Management)',
       'Senior Data Center Engineer',
       'Big Data (HIVE) Engineer – 12 Months Renewable Contract',
       'Assistant /  Engineer – Data Generation',
       'Data Engineer (1 year contract)', 'Software Engineer (Big Data)',
       'Senior Data Engineer', 'Data Center Engineer (Facility)',
       'Senior Systems Engineer – Data Architecture',
       'AVP, Network Engineer (Data & Security), Chief Technology Organization',
       'Data Centre FM Engineer', 'Data Engineer  - Exasol',
       'Data Technical Support Engineer', 'Web Application Developer',
       'Big Data DevOps Engineer',
       'Senior Engineer, Data Loss Protection',
       'Voice / Data / Communication System Engineer', 'DATA ENGINEER',
       'Lead Data Engineer - Business Intelligence',
       'Software Engineer (Data Analysis)',
       'Technical Lead - Big Data, Hadoop', 'Lead Big Data Engineer',
       'Data Integration Architect', 'Data Statistician',
       'SOLUTION ARCHITECT : EDW, BI & Data Integration',
       'Big Data Architect', 'Senior SAP Consultant', 'Data Architect',
       'AVP, Data Architect - Metadata Management, DBS Transformation Group, T&O (WD00640)',
       'VP, Data Architect - Metadata Management, DBS Transformation Group, T&O (WD00640)',
       'Data Architect, Vice President',
       'Hiring for Solution Architect- Product Master Data Management',
       'Senior Data Architect', 'Exasol Architect',
       'Data Solution Director', 'BI / Data Architect',
       'Manager, Clinical Data Management', 'Data Manager (Central Lab)',
       'Assistant Manager, Data Steward for Substantial Shareholding Reporting',
       'Optimisation Specialist',
       'Manager for Process, Systems & Data Management, APAC',
       'Data Center Facilities Manager - Singapore',
       'SAP Data Migration Junior Project Manager',
       'Data Partnership Manager - Group Lifestyle Financing',
       'Data Processing Executive', 'Data Product Manager',
       'IRIS Asia Pricing Master Data and BI - Development Manager',
       'Senior Data Architecture Manager',
       'Project Manager- Data Security', 'Data Solution Manager',
       'Senior Manager - Data Governance & Controls (JD#5029)',
       'ID Administrator',
       'Electrical Manager (Data Centre / Construction)',
       'Facilities Manager, Data Centre',
       'Data Entry cum Admin Assistant',
       'Enterprise Data Management - Market Data Manager',
       'Enterprise Data Management - Data Governance & Valuations Manager',
       'Enterprise Data Management - Data Steward',

#### I'm deleting rows with the following job titles, as they clearly are not part of the data science industry:
- 'Human Resource & Administrative Officer', 'HR cum Admin Assistant [ Kallang Area, 5 Days, 1 Year Exp As HR]', 'HR Practitioner'
- 'Restaurant Manager'
- 'Ethics Manager' 
- 'Account Manager'
- 'IT Audit Manager  /  $7000 Basic + 2VB  /  CBD  /  Immediate !!!'
- 'IT Executive [$4.3k-$4.5k  /  Pioneer  /  SAP Business One  /  Networking  /  Hardware  /  5 days  /  Immediate]'
- 'Sales Executive', 'Sales Development Representative (Japanese)', 'Sales Development Representative (Korean)
- 'Industry Development Manager, I2R / A*STAR'
- 'Software Development Consultant'
- 'Senior Java Developer',  'Java Robotics Developer'
- 'Web Application Developer'
- 'Data Entry cum Admin Assistant'
- 'Faculty Positions in Construction Automation - Civil Engineering'
- 'Senior Manager, Postgraduate Career Services (3-year contract), LKCSB'
- 'Environmental Manager  /  Assistant' 'Space Planner'
- 'Events Sales Manager'
- 'Finance and Admin Executive'
- 'Admin Assistant, Research Department (6 months contract)'
- 'Vice President, Window Security Administrator', 'Financial Controller, South East Asia'

In [37]:
non_data = [
    "Human Resource & Administrative Officer",
    "HR cum Admin Assistant [ Kallang Area, 5 Days, 1 Year Exp As HR]",
    "Restaurant Manager",
    "Ethics Manager",
    "HR Practitioner",
    "Account Manager",
    "IT Audit Manager  /  $7000 Basic + 2VB  /  CBD  /  Immediate !!!",
    "Industry Development Manager, I2R / A*STAR",
    "Software Development Consultant",
    "Faculty Positions in Construction Automation - Civil Engineering",
    "Senior Manager, Postgraduate Career Services (3-year contract), LKCSB",
    "Environmental Manager  /  Assistant",
    "Space Planner",
    "Events Sales Manager",
    "Finance and Admin Executive",
    "Sales Executive",
    "Admin Assistant, Research Department (6 months contract)",
    "Web Application Developer",
    "Data Entry cum Admin Assistant",
    "Sales Development Representative (Japanese)",
    "Sales Development Representative (Korean)",
    "Senior Java Developer",
    "Java Robotics Developer",
    "Vice President, Window Security Administrator",
    "Financial Controller, South East Asia",
    "IT Executive [$4.3k-$4.5k  /  Pioneer  /  SAP Business One  /  Networking  /  Hardware  /  5 days  /  Immediate]",
]

In [38]:
jobs = jobs[~jobs['Title'].isin(non_data)]

In [39]:
jobs.shape

(905, 11)

#### I'm reasonably satisfied with the preliminary data cleaning, so I'll output it to a new file for visualisation and modelling.

In [40]:
#jobs_clean = jobs.to_csv('../data/jobs_clean.csv', index=False)

#### Data Viz for NLP-related projects tend to generate huge files, so I'll do that from a new notebook in 1.2